// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cov_evals_inside_cpp
double cov_evals_inside_cpp(const arma::colvec& vj, const arma::colvec& vk, const arma::mat& dupmat, const arma::mat& mcov);
RcppExport SEXP _PivotalBootstrapMatrixData_cov_evals_inside_cpp(SEXP vjSEXP, SEXP vkSEXP, SEXP dupmatSEXP, SEXP mcovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type vj(vjSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type vk(vkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dupmat(dupmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mcov(mcovSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_evals_inside_cpp(vj, vk, dupmat, mcov));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PivotalBootstrapMatrixData_cov_evals_inside_cpp", (DL_FUNC) &_PivotalBootstrapMatrixData_cov_evals_inside_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PivotalBootstrapMatrixData(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
