# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
#' @title Helper for cov_evals().
#' @description Cpp version of `cov_evals_inside()`
#' @return Single numeric value
cov_evals_inside_cpp <- function(vj, vk, dupmat, mcov) {
    .Call('_TFORGE_cov_evals_inside_cpp', PACKAGE = 'TFORGE', vj, vk, dupmat, mcov)
}

